### ISSUE TITLE
Example jdbcurl is not supported by the driver

### ISSUE THREAD

**Issue by jaakko-solita** [DiceTechnology/dice-fairlink#23]
Current: `jdbc:auroraro:mysql//my-cluster/my-schema`
Should be: `jdbc:auroraro:mysql://my-cluster/my-schema`

**Comment by gedl** [comment]
hi @jaakko-solita 

Well spotted. thanks.

I resolved this with 73764cbd96b4988d5a5084976002308d49474cc3
