### ISSUE TITLE
General Guidance with HikariCP

### ISSUE THREAD

**Issue by ttj4** [DiceTechnology/dice-fairlink#42]
I am trying to make dice-fairlink library work with HikariCP. First of all, is this something possible? I couldn't find any resources to verify the same.

**Comment by AndreyLebedenko** [comment]
Yes, it is compatible with HikariCP.

**Comment by ttj4** [comment]
@AndreyLebedenko thanks for the reply. I am using the following configuration:
`{
      jdbcUrl="jdbc:fairlink:mysql://mytest-ro-random.us-east-1.rds.amazonaws.com/mydb"
      dataSource.user="root"
      dataSource.password="root"
      driverClassName="technology.dice.dicefairlink.driver.AuroraReadReplicasDriver"

      maximumPoolSize=20
      minimumIdle=5
      idleTimeout=30000
      poolName="test-audit"

      discoveryMode="SQL_MYSQL"
      auroraClusterRegion="us-east-1"
    }`
but keeps on getting errors like `Error in custom provider, java.lang.RuntimeException: Property discoveryMode does not exist on target class me.socure.common.hikari.cp.HikariConfig`
looks like HikariConfig is looking for set/get methods for the properties. Does it mean I have to comeup with a custom wrapper on top of HikariConfig with all the additional setters and getters?

**Comment by AndreyLebedenko** [comment]
Looks like you are trying to put `discoveryMode` into the Hikari config. If so, this is not how JDBC driver properties are passed.
The standard approach is either to pass them in the separate `Properties` structure or directly in URL.

See an example for PostgreSQL (from https://jdbc.postgresql.org/documentation/head/connect.html)
```
String url = "jdbc:postgresql://localhost/test";
Properties props = new Properties();
props.setProperty("user","fred");
props.setProperty("password","secret");
props.setProperty("ssl","true");
Connection conn = DriverManager.getConnection(url, props);
```

```
String url = "jdbc:postgresql://localhost/test?user=fred&password=secret&ssl=true";
Connection conn = DriverManager.getConnection(url);
```
(

**Comment by ttj4** [comment]
@AndreyLebedenko I feel so stupid for not realizing I should have passed it as driver properties. It's working now. Thanks for pointing me in the right direction.

**Comment by gedl** [comment]
Thanks @AndreyLebedenko ! I hope you're great.

@ttj4 which database are you using? There's an old PR that has been pending for way too long, which is PostreSQL related, so it may be worth for us to have a look at merging it if you're using PostgreSQL.

**Comment by ttj4** [comment]
@gedl I am using Aurora MySQL, we are having uneven loads across different replica instances. After some digging, I ended up here.

**Comment by gedl** [comment]
Yeah, same problem that lead us to write it in the first place. You've come to the right place.

Please let us know if you find something you'd like see fixed and/or improved.

**Comment by ttj4** [comment]
on second thought, I think if you could merge the Postgres changes would be awesome.
Btw, what happens if someone uses `AWSSecretsManagerMySQLDriver` (ie: they have the actual password on AWS sm). Is it something possible to bring here?

**Comment by gedl** [comment]
I didn't know about that driver. Seems to follow the same concept, with a jdbc sub-protocol, so it wouldn't be possible to compose them as it stands. 

Shouldn't be hard to allow this, though. 

We'll look into merging that PostreSQL PR. The new version of Aurora seems to have fixed the node discovery meta-table which is a good timing for us to touch related code, as we can now stop using the RDS control plane to describe the cluster.

**Comment by gedl** [comment]
@ttj4 if there's nothing else to discuss here, could you please close the issue? 

Thanks
